In [1]:
import numpy as np

In [2]:
with open("input.txt", "r") as f:
    input = f.readlines()
input = [np.array(list(map(int, l.strip().split(' ')))) for l in input]
input

[array([65, 68, 71, 72, 71]),
 array([31, 34, 36, 37, 37]),
 array([80, 83, 84, 86, 87, 90, 92, 96]),
 array([30, 33, 36, 39, 45]),
 array([21, 22, 25, 23, 24]),
 array([66, 68, 69, 71, 72, 71, 72, 69]),
 array([2, 3, 5, 4, 4]),
 array([77, 78, 77, 79, 82, 83, 86, 90]),
 array([ 6,  9, 10,  7,  9, 12, 17]),
 array([25, 27, 28, 28, 30, 32]),
 array([61, 63, 66, 68, 68, 66]),
 array([51, 54, 54, 57, 60, 60]),
 array([50, 52, 52, 53, 56, 60]),
 array([73, 75, 76, 76, 83]),
 array([19, 20, 24, 26, 28]),
 array([36, 38, 41, 42, 45, 49, 47]),
 array([56, 59, 63, 64, 64]),
 array([26, 29, 32, 36, 40]),
 array([70, 72, 74, 75, 77, 80, 84, 89]),
 array([81, 83, 88, 89, 92, 95, 96]),
 array([79, 80, 85, 87, 89, 92, 93, 90]),
 array([77, 80, 85, 87, 89, 92, 92]),
 array([29, 31, 33, 38, 40, 42, 46]),
 array([49, 52, 57, 58, 59, 65]),
 array([14, 11, 14, 17, 18, 19]),
 array([43, 40, 41, 44, 47, 50, 51, 50]),
 array([31, 30, 32, 35, 35]),
 array([43, 40, 42, 43, 46, 49, 51, 55]),
 array([ 9,  7,  

In [3]:
def safe(array):
    monotonic = False
    if np.all(array == np.sort(array)) or np.all(array == np.flip(np.sort(array))):
        monotonic = True
    differences = np.abs(array[:-1]-array[1:])
    diffs_bad = False
    if np.max(differences) > 3 or np.min(differences) == 0:
        diffs_bad = True
    if monotonic and not diffs_bad:
        return True
    else:
        return False

In [4]:
count = 0
for array in input:
    if safe(array):
        count += 1
    else:
        for idx in len(array):
            if safe
count

269