In [37]:
import numpy as np
import itertools

In [38]:
with open('input.txt') as f:
    data = f.readlines()

heights = []
for line in data:
    height = []
    for char in line.strip():
        height.append(int(char))
    heights.append(height)
heights = np.array(heights)
print(heights.shape)
heights

(40, 40)


array([[0, 9, 8, ..., 1, 2, 3],
       [1, 2, 9, ..., 4, 3, 4],
       [2, 3, 4, ..., 5, 2, 1],
       ...,
       [5, 8, 9, ..., 6, 5, 0],
       [0, 1, 2, ..., 7, 8, 9],
       [1, 0, 3, ..., 6, 7, 8]])

In [39]:
trailheads = []
for y, row in enumerate(heights):
    for x, height in enumerate(row):
        if height == 0:
            trailheads.append(np.array([x,y]))
trailheads

[array([0, 0]),
 array([11,  0]),
 array([13,  0]),
 array([23,  0]),
 array([36,  0]),
 array([12,  1]),
 array([29,  1]),
 array([4, 2]),
 array([19,  2]),
 array([27,  2]),
 array([30,  2]),
 array([8, 3]),
 array([9, 3]),
 array([13,  3]),
 array([19,  3]),
 array([20,  3]),
 array([30,  3]),
 array([33,  3]),
 array([37,  3]),
 array([39,  3]),
 array([4, 4]),
 array([16,  4]),
 array([31,  4]),
 array([34,  4]),
 array([37,  4]),
 array([3, 5]),
 array([9, 5]),
 array([12,  5]),
 array([24,  5]),
 array([36,  5]),
 array([0, 6]),
 array([4, 6]),
 array([19,  6]),
 array([0, 7]),
 array([36,  7]),
 array([10,  8]),
 array([16,  8]),
 array([24,  8]),
 array([31,  8]),
 array([7, 9]),
 array([13,  9]),
 array([27,  9]),
 array([14, 10]),
 array([33, 10]),
 array([ 2, 11]),
 array([ 5, 11]),
 array([15, 11]),
 array([19, 11]),
 array([23, 11]),
 array([26, 11]),
 array([34, 11]),
 array([10, 12]),
 array([ 3, 13]),
 array([11, 13]),
 array([25, 13]),
 array([26, 13]),
 array([35, 13

In [40]:
shifts = (np.array([1, 0]), np.array([-1, 0]), np.array([0, 1]), np.array([0, -1]))
def get_nearby_cells(start_pos):
    nearby = []
    for shift in shifts:
        pos = start_pos + shift
        if np.all(pos >= 0) and np.all(pos < heights.shape):
            nearby.append(pos)
    return nearby

In [41]:
def is_valid_path(path):
    #print(path)
    for idx, pos in enumerate(path):
        #print(idx, pos)
        if idx == 9:
            return True
        if not any((path[idx+1] == x).all() for x in get_nearby_cells(pos)):
            return False

In [42]:
total = 0
for trailhead in trailheads:
    map = -np.ones_like(heights)
    map[trailhead[1], trailhead[0]] = 0
    current_pos = [trailhead]
    heights_dict = {0: current_pos}
    #print(f'start {trailhead}')
    for current_height in range(1, 10):
        new_pos = []
        for pos in current_pos:
            nearby_cells = get_nearby_cells(pos)
            for cell in nearby_cells:
                if map[cell[1], cell[0]] == -1 and heights[cell[1], cell[0]] == current_height:
                    map[cell[1], cell[0]] = current_height
                    new_pos.append(cell)
        current_pos = new_pos
        heights_dict[current_height] = current_pos
        #print(current_height, current_pos)
    #print(map >= 0)
    #print(heights == 9)
    #print(heights_dict)
    for path in itertools.product(heights_dict[0], heights_dict[1], heights_dict[2], heights_dict[3], heights_dict[4], heights_dict[5], heights_dict[6], heights_dict[7], heights_dict[8], heights_dict[9]):
        if is_valid_path(path):
            #print(path)
            total += 1
    #total += np.count_nonzero(np.logical_and(map >= 0, heights == 9))
total

928