In [2]:
import numpy as np

In [3]:
with open("input_small.txt") as f:
    lines = f.readlines()
data = [[ord(char) for char in line.strip()] for line in lines]
data = np.array(data)
data

array([[82, 82, 82, 82, 73, 73, 67, 67, 70, 70],
       [82, 82, 82, 82, 73, 73, 67, 67, 67, 70],
       [86, 86, 82, 82, 82, 67, 67, 70, 70, 70],
       [86, 86, 82, 67, 67, 67, 74, 70, 70, 70],
       [86, 86, 86, 86, 67, 74, 74, 67, 70, 69],
       [86, 86, 73, 86, 67, 67, 74, 74, 69, 69],
       [86, 86, 73, 73, 73, 67, 74, 74, 69, 69],
       [77, 73, 73, 73, 73, 73, 74, 74, 69, 69],
       [77, 73, 73, 73, 83, 73, 74, 69, 69, 69],
       [77, 77, 77, 73, 83, 83, 74, 69, 69, 69]])

In [4]:
shifts = (np.array([1, 0]), np.array([-1, 0]), np.array([0, 1]), np.array([0, -1]))
def get_nearby_cells(start_pos):
    nearby = []
    for shift in shifts:
        pos = start_pos + shift
        if np.all(pos >= 0) and np.all(pos < data.shape):
            nearby.append([int(x) for x in pos])
    return nearby

def get_borders(start_pos):
    borders = []
    region = regions[start_pos[1], start_pos[0]]
    for shift in shifts:
        pos = start_pos + shift
        if np.all(pos >= 0) and np.all(pos < regions.shape):
            if region != regions[pos[1], pos[0]]:
                borders.append([int(x) for x in pos])
        else:
            borders.append([int(x) for x in pos])
    return borders

In [5]:
region_to_plant = {}
region_to_coords = {}
regions = np.zeros_like(data)
regions
n_regions = 0
while True:
    for y, row in enumerate(regions):
        for x, region in enumerate(row):
            if region == 0:
                break
        if region == 0:
            break
    if region == 0:
        n_regions += 1
        current_plant = data[y, x]
        region_to_plant[n_regions] = current_plant
        region_to_coords[n_regions] = [[x, y]]
        regions[y, x] = n_regions
        while True:
            changed = False
            for pos in region_to_coords[n_regions]:
                nearbys = get_nearby_cells(pos)
                for nearby in nearbys:
                    if nearby not in region_to_coords[n_regions] and data[nearby[1], nearby[0]] == current_plant:
                        changed = True
                        region_to_coords[n_regions].append(nearby)
                        regions[nearby[1], nearby[0]] = n_regions
            if not changed:
                break
        #break
    else:
        break
print(regions)
print(region_to_plant)
print(region_to_coords)

[[ 1  1  1  1  2  2  3  3  4  4]
 [ 1  1  1  1  2  2  3  3  3  4]
 [ 5  5  1  1  1  3  3  4  4  4]
 [ 5  5  1  3  3  3  6  4  4  4]
 [ 5  5  5  5  3  6  6  7  4  8]
 [ 5  5  9  5  3  3  6  6  8  8]
 [ 5  5  9  9  9  3  6  6  8  8]
 [10  9  9  9  9  9  6  6  8  8]
 [10  9  9  9 11  9  6  8  8  8]
 [10 10 10  9 11 11  6  8  8  8]]
{1: np.int64(82), 2: np.int64(73), 3: np.int64(67), 4: np.int64(70), 5: np.int64(86), 6: np.int64(74), 7: np.int64(67), 8: np.int64(69), 9: np.int64(73), 10: np.int64(77), 11: np.int64(83)}
{1: [[0, 0], [1, 0], [0, 1], [2, 0], [1, 1], [3, 0], [2, 1], [3, 1], [2, 2], [3, 2], [2, 3], [4, 2]], 2: [[4, 0], [5, 0], [4, 1], [5, 1]], 3: [[6, 0], [7, 0], [6, 1], [7, 1], [6, 2], [8, 1], [5, 2], [5, 3], [4, 3], [3, 3], [4, 4], [4, 5], [5, 5], [5, 6]], 4: [[8, 0], [9, 0], [9, 1], [9, 2], [8, 2], [9, 3], [7, 2], [8, 3], [7, 3], [8, 4]], 5: [[0, 2], [1, 2], [0, 3], [1, 3], [0, 4], [1, 4], [0, 5], [2, 4], [1, 5], [0, 6], [3, 4], [1, 6], [3, 5]], 6: [[6, 3], [6, 4], [5, 4], [

In [9]:
diag_shifts = (np.array([1, 1]), np.array([-1, -1]), np.array([-1, 1]), np.array([1, -1]))
def get_diag_cells(start_pos):
    nearby = []
    for shift in diag_shifts:
        pos = start_pos + shift
        if np.all(pos >= 0) and np.all(pos < data.shape):
            nearby.append([int(x) for x in pos])
    return nearby

def get_vertices(start_pos):
    borders = []
    region = regions[start_pos[1], start_pos[0]]
    for shift in shifts:
        pos = start_pos + shift
        if np.all(pos >= 0) and np.all(pos < regions.shape):
            if region != regions[pos[1], pos[0]]:
                borders.append([int(x) for x in pos])
        else:
            borders.append([int(x) for x in pos])
    return borders

get_diag_cells([1, 1])

[[2, 2], [0, 0], [0, 2], [2, 0]]

In [7]:
total = 0
for region, coords in region_to_coords.items():
    #print(region, coords)
    borders = []
    for coord in coords:
        for border in get_borders(coord):
            borders.append(border)
    area = len(coords)
    borders = list(set(map(tuple, borders)))
    print(borders)
    perimeter = len(borders)
    total += area*perimeter
    print(area, perimeter, area*perimeter)
print(total)

[(2, -1), (1, 3), (1, 2), (4, 0), (3, -1), (2, 4), (4, 1), (4, 3), (-1, 1), (1, -1), (-1, 0), (0, 2), (3, 3), (0, -1), (5, 2)]
12 15 180
[(3, 1), (5, -1), (6, 1), (4, 2), (3, 0), (6, 0), (4, -1), (5, 2)]
4 8 32
[(3, 4), (5, 4), (4, 6), (5, 1), (8, 0), (5, 7), (7, -1), (6, 5), (4, 2), (5, 0), (8, 2), (9, 1), (6, -1), (3, 2), (3, 5), (2, 3), (7, 2), (6, 6), (6, 3)]
14 19 266
[(7, 4), (6, 2), (8, -1), (7, 1), (8, 1), (7, 0), (10, 1), (10, 0), (9, -1), (6, 3), (10, 3), (8, 5), (10, 2), (9, 4)]
10 14 140
[(0, 1), (0, 7), (4, 4), (-1, 4), (1, 1), (2, 3), (1, 7), (3, 3), (-1, 3), (2, 5), (2, 6), (2, 2), (-1, 6), (4, 5), (3, 6), (-1, 2), (-1, 5)]
13 17 221
[(4, 4), (7, 4), (6, 2), (5, 5), (5, 8), (8, 7), (5, 7), (7, 3), (7, 9), (5, 6), (8, 6), (6, 10), (5, 3), (5, 9), (8, 5), (7, 8)]
11 16 176
[(7, 5), (8, 4), (6, 4), (7, 3)]
1 4 4
[(9, 10), (10, 5), (8, 4), (7, 7), (9, 3), (10, 8), (10, 4), (6, 8), (7, 10), (8, 10), (10, 7), (7, 6), (10, 6), (10, 9), (7, 5), (6, 9)]
13 16 208
[(0, 7), (2, 4),