In [1]:
import numpy as np

In [2]:
with open('input_small.txt') as f:
    lines = f.readlines()
map = np.zeros((len(lines), len(lines[0].strip())), dtype=int)
current_direction = 0
for y, line in enumerate(lines):
    for x, char in enumerate(line.strip()):
        if char == "#":
            map[y, x] = 1
        elif char == "^":
            current_position = np.array([y, x])
        
print(map)
print(current_position)
print(current_direction)

[[0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]
[6 4]
0


In [3]:
def get_one_ahead(position, direction, maximum):
    position = position.copy()
    if direction == 0:
        position[0] -= 1
    elif direction == 1:
        position[1] += 1
    elif direction == 2:
        position[0] += 1
    elif direction == 3:
        position[1] -= 1
    if np.max(position) >= maximum or np.min(position) < 0:
        return False
    else:
        return position

In [4]:
one_ahead = get_one_ahead(current_position, current_direction, map.shape[0])
visited = []
visited.append(current_position.copy())
counter = 0
while one_ahead is not False:
    counter += 1
    if counter > 10000:
        break
    #print(current_position, current_direction, one_ahead)
    #print(map[one_ahead[0], one_ahead[1]])
    if map[one_ahead[0], one_ahead[1]] == 1:
        #print('wall')
        current_direction += 1
        if current_direction == 4:
            current_direction = 0
        one_ahead = get_one_ahead(current_position, current_direction, map.shape[0])
        continue
    current_position = one_ahead
    #print(current_position, visited, any((current_position == x).all() for x in visited))
    if not any((current_position == x).all() for x in visited):
        visited.append(current_position.copy())
    one_ahead = get_one_ahead(current_position, current_direction, map.shape[0])
    
print(current_position)
print(len(visited))

[9 7]
41
