In [35]:
import numpy as np

In [46]:
data = np.loadtxt('input.txt', dtype=str)
data = data.view(np.int32).reshape((data.shape[0], -1))
print(data)
xmas = np.array(['XMAS'], dtype=str).view(np.int32)
print(xmas)

[[77 83 83 ... 77 88 88]
 [65 65 77 ... 77 65 77]
 [77 77 83 ... 77 88 65]
 ...
 [77 65 77 ... 83 83 77]
 [77 77 77 ... 77 88 65]
 [83 88 83 ... 83 65 83]]
[88 77 65 83]


In [47]:
sum = 0
for x in np.arange(0, data.shape[1]-2):
    for y in np.arange(0, data.shape[0]-2):
        square = data[y:y+3,x:x+3]
        if square[1][1] == 65:
            if square[0][0] == 77 and square[0][2] == 77 and square[2][0] == 83 and square[2][2] == 83:
                #print('a')
                #print(square)
                sum += 1
            if square[0][0] == 77 and square[0][2] == 83 and square[2][0] == 77 and square[2][2] == 83:
                #print('b')
                #print(square)
                sum += 1
            if square[0][0] == 83 and square[0][2] == 83 and square[2][0] == 77 and square[2][2] == 77:
                #print('c')
                #print(square)
                sum += 1
            if square[0][0] == 83 and square[0][2] == 77 and square[2][0] == 83 and square[2][2] == 77:
                #print('d')
                #print(square)
                sum += 1
print(sum)
# 1931 high

1807
